draw_set_font(fnt_dialogue);
text = "...";
xBuffer = 10;
yBuffer = 10;
boxHeight = camera_get_view_height(view_camera[0]);
boxWidth = camera_get_view_width(view_camera[0]);
stringHeight = string_height(text);
creator = noone;
charCount = 0;
name = noone;
_pagecomplete = false;